version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
     # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - ./etc-dnsmasq.d:/etc/dnsmasq.d"
    dns:
            - 172.18.0.3
            - 1.1.1.1
    networks:
          - cloudflared
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    restart: unless-stopped
    environment:
        TZ: 'America/Chicago'
        WEBPASSWORD: <password from pw manager>
        DNSMASQ_LISTENING: 'all'  # needed to listen on all interfaces permit all origins

networks:
  cloudflared:
      name: cloudflared