name: pihole

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
     # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - ./etc-dnsmasq.d:/etc/dnsmasq.d"
    networks:
          - cloudflared
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    restart: unless-stopped
    environment:
        TZ: 'America/Chicago'
        WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
        DNSMASQ_LISTENING: 'all'  # needed to listen on all interfaces permit all origins
        PIHOLE_DNS_: 127.0.0.1#${LOCAL_PIHOLE_DNS_PORT};${DNS_1};${DNS_2}
        DHCP_ACTIVE: 'false'
        WEBTHEME: 'default-auto'
        

networks:
  cloudflared:
      name: cloudflared
      external: true
