version: '2'
services:
  cloudflared:
      image: msnelling/cloudflared
      container_name: cloudflared-host
      volumes:
          - ./config:/etc/cloudflared
      command: /usr/local/bin/cloudflared tunnel --no-autoupdate run --token <token from pw manager>
      dns:
            - 127.0.0.1
            - 1.1.1.1
      network_mode: "host"