version: '3.7'
services:
  cloudflared:
      image: ${CLOUDFLARED_IMAGE}
      container_name: cloudflared-host
      command: /usr/local/bin/cloudflared tunnel --no-autoupdate run
      environment:
        TUNNEL_TOKEN: ${HOST_TUNNEL_TOKEN}
      network_mode: "host"