version: '2'
services:
  cloudflared:
      image: msnelling/cloudflared
      container_name: cloudflared-host
      volumes:
          - ./config:/etc/cloudflared
      command: /usr/local/bin/cloudflared tunnel --no-autoupdate run --token <replace with your token here>
      network_mode: "host"