version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx
        volumes:
            # content
            - type: bind
              source: /var/www
              target: /usr/share/nginx/html
              read_only: true
            
            # nginx config files  
            - type: bind
              source: /var/nginx/conf
              target: /etc/nginx/conf.d
              read_only: true
        dns:
            - 127.0.0.1
            - 172.18.0.4
            - 1.1.1.1
        networks:
            - cloudflared

networks:
    cloudflared:
        external: true
        name: cloudflared