version: '3.7'
services:
  cloudflared:
      image: ${CLOUDFLARED_IMAGE}
      container_name: cloudflared
      command: /usr/local/bin/cloudflared tunnel --no-autoupdate run
      environment:
        TUNNEL_TOKEN: ${CAMERA_TUNNEL_TOKEN}
      networks:
        - cloudflared
networks:
  cloudflared:
      name: cloudflared