version: '2'
services:
  cloudflared:
      image: msnelling/cloudflared
      container_name: cloudflared
      volumes:
          - ./config:/etc/cloudflared
      command: /usr/local/bin/cloudflared tunnel --no-autoupdate run --token <replace with your token here>
      networks:
        - cloudflared
networks:
  cloudflared:
      name: cloudflared